//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Email = new HashSet<Email>();
            this.Facture = new HashSet<Facture>();
            this.Reservation = new HashSet<Reservation>();
            this.Telephone = new HashSet<Telephone>();
        }
    
        public int Id { get; set; }
        public string Civilite { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public bool CarteFidelite { get; set; }
        public string Societe { get; set; }
    
        public virtual Adresse Adresse { get; set; }
        public virtual ICollection<Email> Email { get; set; }
        public virtual ICollection<Facture> Facture { get; set; }
        public virtual ICollection<Reservation> Reservation { get; set; }
        public virtual ICollection<Telephone> Telephone { get; set; }
    }
}
