//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Client
    {

        [Key]
        public int Id { get; set; }
        public string Civilite { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public bool CarteFidelite { get; set; }
        public string Societe { get; set; }
    
        public virtual Adresse Adresse { get; set; }
        public virtual ICollection<Email> Email { get; set; }
        public virtual ICollection<Facture> Facture { get; set; }
        public virtual ICollection<Reservation> Reservation { get; set; }
        public virtual ICollection<Telephone> Telephone { get; set; }
    }
}
