//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public class Facture
    {
        public Facture()
        {
            this.LigneFacture = new HashSet<LigneFacture>();
        }
    
        public int Id { get; set; }
        public int IdClient { get; set; }
        public System.DateTime DateFacture { get; set; }
        public Nullable<System.DateTime> DatePaiement { get; set; }
        public string CodeModePaiement { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ModePaiement ModePaiement { get; set; }
        public virtual ICollection<LigneFacture> LigneFacture { get; set; }
    }
}
