//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModePaiement
    {
        public ModePaiement()
        {
            this.Facture = new HashSet<Facture>();
        }
    
        public string Code { get; set; }
        public string Libelle { get; set; }
    
        public virtual ICollection<Facture> Facture { get; set; }
    }
}
