//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GrandHotelEntities : DbContext
    {
        public GrandHotelEntities()
            : base("name=GrandHotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Adresse> Adresse { get; set; }
        public DbSet<Calendrier> Calendrier { get; set; }
        public DbSet<Chambre> Chambre { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<Email> Email { get; set; }
        public DbSet<Facture> Facture { get; set; }
        public DbSet<LigneFacture> LigneFacture { get; set; }
        public DbSet<ModePaiement> ModePaiement { get; set; }
        public DbSet<Reservation> Reservation { get; set; }
        public DbSet<Tarif> Tarif { get; set; }
        public DbSet<Telephone> Telephone { get; set; }
    }
}
